### ISSUE TITLE
Fatal exception of type "Error"

### ISSUE THREAD

**Issue by AbelLykens** [pseudozach/LightningPayment#2]
Trying to enable LightningPayment on lightningwiki.net 😁

Using lnbits, I do have parserfunctions. I get:

In browser:
```
[X-3gf2hpnxF@Ry5x2c0VrAAAAAI] 2021-01-12 17:46:40: Fatal exception of type "Error"
```

Logs:
```
[Tue Jan 12 17:46:40.651207 2021] [php7:notice] [pid 59782] [client 185.220.101.218:12388] PHP Notice:  Undefined variable: expiry in /var/www/mediawiki-1.31.1/extensions/LightningPayment/LightningPayment.body.php on line 299, referer: https://lightningwiki.net/index.php/Special:SpecialPages
```

any thoughts?

**Comment by AbelLykens** [comment]
Seems to work! Could you try on lightningwiki.net ?

**Comment by pseudozach** [comment]
> Seems to work! Could you try on lightningwiki.net ?

great! Just tested it. It does work!
Can you share which version did not work for you? maybe I need to put at least X version as a requirement.

**Comment by AbelLykens** [comment]
I was on mediawiki-1.35.1

**Comment by pseudozach** [comment]
Thanks!
